version: "2"
services:
  webapp:
    depends_on:
      - postgres
    container_name: voting_webapp
    restart: always
    build:
      context: .
      dockerfile: ./webapp/Dockerfile
    volumes:
      - ./webapp:/webapp
    ports:
      - "476:80"

  postgres:
    image: postgres
    env_file:
      - database.env
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data: